#!/bin/sh 

  ######## gzip ########
     gzip $(ls -lrt path_log | grep $(date -d '7 day ago' +'%Y%m%d')/*)
  
  ####### Romove log #####
     n_days=$(date -d "1 month ago" +%Y%m%d)
     list="/opt/Assign/Log/"

     for f in $(ls -d $list[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]* | xargs -n 1 basename | tr -d ":" )
     do
          (( $f <= $n_days )) && rm -rf "$list$f"
     done
